### PR TITLE
Fix run action

### LINKED ISSUE #89: flogo build fails with runaction contribution
When trying to build my flogo project with `github.com/project-flogo/contrib/activity/runaction`contribution installed, I get the following errror:

```
flogo build

Error building project: go: finding github.com/project-flogo/core/runner latest
C:\Users\ppaidi\goworkspace\pkg\mod\github.com\project-flogo\contrib\activity\runaction@v0.0.0-20191128033334-83001eea3c14\activity.go:12:2: unknown import path "github.com/project-flogo/core/runner": cannot find module providing package github.com/project-flogo/core/runner
```

### PR DESCRIPTION
**Pull request by skothari-tibco**
Fixes #89

### CODE REVIEW

File: activity/runaction/metadata.go [hunk 1]
```diff
@@ -5,9 +5,9 @@ import (
 )
 
 type Settings struct {
-	Ref    string `md:"ref,required"` //The ref to action
-	UriType string `md:"uriType,required"`
-	ResURI string `md:"resURI,required"`
+	Ref     string `md:"ref,required"` //The ref to action
+	UriType string `md:"uriType,required,allowed(flowURI,catalystMlURI)"`
```
Comment (fm-tibco) [inline activity/runaction/metadata.go]: This cannot be fixed.  Not sure you even need this.  You documentation should just mention that you need to use the settings of the action you are trying to run.   Maybe make your Settings be 
```
type Settings struct {
  ActionRef    string `md:"actionRef,required"` //The ref to action		Ref     string `md:"ref,required"` //The ref to action
  ActionSettings map[string]interface{} `md:"actionSettings,required"`	```

Comment (skothari-tibco) [reply activity/runaction/metadata.go]: Yes, that was a band aid to the issue. Action Settings looks a nice way to go. I'll change according to that. Thanks
